apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: indodanazwide-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{APP_DOMAIN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: indodanazwide-service
                port:
                  number: 80