apiVersion: v1
kind: Service
metadata:
  name: indodanazwide-service
spec:
  selector:
    app: indodanazwide
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
